# Site settings
title: Office of Evaluation Sciences
description: The Office of Evaluation Sciences (OES) is a team of applied experts based at the General Services Administration (GSA) that combines academic expertise with experience implementing and evaluating evidence-based program changes to quickly learn what works, what works best, and what does not work.
url: "https://oes.gsa.gov" # the base hostname & protocol for your site
logo: /assets/img/logos/logo-name.png
feature_image: /assets/img/Kites-small.jpg
permalink: pretty

# Site theme
theme: uswds-jekyll

# Styles
styles:
  - /assets/css/main.css

# Collections
collections:
  projects:
    output: true
  team:
    output: true

defaults:
  - scope:
      path: ''
      type: projects
    values:
      layout: project-single
  - scope:
      path: ''
      type: team
    values:
      layout: team-single

colors:
  primary: '#0071bc'

analytics:
  google:
    code: 'UA-67580537-1'
  dap:
    agency: GSA
    subagency: SBST

forms:
- type: newsletter
    button: Sign up
      url: https://docs.google.com/forms/d/e/1FAIpQLScFqOQbifXJG5rSlt-OLetNP3qTJBgT7hPik8TPW6lD1APMHQ/viewform
  privacypolicy:
    name: GSA Privacy and Security Notice
    url: https://gsa.gov

footer:
  image: /assets/img/icons/gsa-white.svg
  email: oes@gsa.gov
  twitter:
    - usgsa
  text:

# Build settings
include:
  - _navigation.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - Gemfile
  - Gemfile.lock
