# Site settings
title: Office of Evaluation Sciences
description: The Office of Evaluation Sciences (OES) brings diverse scientific expertise to Federal agencies to apply insights about human behavior to improve Government’s interactions with people, test and learn what works using rigorous methods.
url: "https://oes.gsa.gov" # the base hostname & protocol for your site
logo: /assets/img/logos/logo-name.png
feature_image: /assets/img/Kites-small.jpg
permalink: pretty

# Site theme
theme: uswds-jekyll

# Styles
styles:
  - /assets/css/main.css

# Collections
collections:
  projects:
    output: true
  team:
    output: true

defaults:
  - scope:
      path: ''
      type: projects
    values:
      layout: project-single
  - scope:
      path: ''
      type: team
    values:
      layout: team-single

colors:
  primary: '#0071bc'

analytics:
  google:
    code: 'UA-67580537-1'
  dap:
    agency: GSA
    subagency: SBST

forms:
- type: newsletter
  url: https://docs.google.com/forms/d/1Tsdm_2spbxWnmTFMrH5eHxpOAN9W4LB3eaMMXJ1N0rU/formResponse
  button: Subscribe
  privacypolicy:
    name: GSA Privacy and Security Notice
    url: https://gsa.gov
  fields:
    - type: email
      name: entry.1440502332
      label: Enter you email address
    - type: hidden
      name: fbzx
      value: -7861934959779167198

footer:
  image: /assets/img/icons/gsa-white.svg
  email: oes@gsa.gov
  twitter:
    - usgsa
  text:

# Build settings
include:
  - _navigation.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - Gemfile
  - Gemfile.lock
